### ISSUE TITLE
Cannot import OGCGeometry enum

### ISSUE THREAD

**Issue by rooby** [mapbox/shp-write#103]
When you import OGCGeometry it fails with this error
```
Error: export
 'OGCGeometry' (imported as 'OGCGeometry') was not found in '@mapbox/shp-write' (possible exports: download,
 write, zip)
```

**Comment by sheindel** [comment]
I'm good with the `type` you proposed in your PR but for curiosity sake I wonder if a `const enum` would have worked?

I think I missed these because I have `skipLibCheck: true` in my primary project that uses this so I need to turn that off to better check these types like you did. I'll give it a shot.

Thanks for contributing!

**Comment by rooby** [comment]
In this case `const enum` doesn't work because then when you pass in something like `OGCGeometry.POLYLINE` it will pass in the enum value of `3` instead of the enum key of `POLYLINE`.
To do that the code that uses the enum would have to change to accept the number instead of the name.

**Comment by sheindel** [comment]
Ah that makes sense. Man, why do enums have to be so odd in Typescript? This reminds me why I've been using the pattern of an array `as const` and adding a type with `keyof MyArray[number]`

I'll close this issue once we release your fixes, thanks again!
